# /etc/kubernetes/pki/etcd/ca.crt & healthcheck-client.crt & healthcheck-client.key
sudo kubectl -n monitoring create secret generic etcd-certs --from-file=CREDENTIAL_PATH/etcd-client.pem --from-file=CREDENTIAL_PATH/etcd-client-key.pem --from-file=CREDENTIAL_PATH/ca.pem`
curl --cacert ./ca.pem --cert ./etcd-client.pem --key ./etcd-client-key.pem https://127.0.0.1:2379/metrics
kubectl -n monitoring create secret generic etcd-certs --from-file=./etcd-client.pem --from-file=./etcd-client-key.pem --from-file=./ca.pem

Edit prometheus-operator/contrib/kube-prometheus/manifests/prometheus/prometheus-k8s.yaml and add the secret under the spec of the Prometheus object manifest:

```
  secrets: 
  - etcd-certs
```

The manifest will look like that:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 2
  secrets: 
  - etcd-certs
  version: v1.7.0
  
  If your Prometheus Operator is already in place, update it:

`kubectl -n monitoring replace -f contrib/kube-prometheus/manifests/prometheus/prometheus-k8s.yaml

